version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: exercicio-tecnico-elotech
    volumes:
      - postgres:/data/postgres
    networks:
      - exercicio-tecnico-elotech
    hostname: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: contato.diego.prandini@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - exercicio-tecnico-elotech
    hostname: pgadmin
    depends_on:
      - postgres

  # exercicio-tecnico-elotech:
  #   container_name: exercicio-tecnico-elotech
  #   image: exercicio-tecnico-elotech:latest
  #   build: .
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     JAVA_TOOL_OPTIONS: >
  #       -Dserver.port=8080
  #       -Dspring.profiles.active=dev
  #       -Dspring.datasource.url=jdbc:postgresql://postgres:5432/exercicio-tecnico-elotech
  #       -Dspring.datasource.username=postgres
  #       -Dspring.datasource.password=postgres
  #   networks:
  #     - exercicio-tecnico-elotech
  #   hostname: exercicio-tecnico-elotech
  #   depends_on:
  #     - postgres
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - exercicio-tecnico-elotech
    hostname: mongo

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo:27017/
    volumes:
      - mongo:/data/db
    links:
      - mongo
    networks:
      - exercicio-tecnico-elotech
    hostname: mongo-express
    depends_on:
      - mongo

networks:
  exercicio-tecnico-elotech:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
