server:
  error:
    include-stacktrace: on_param

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exercicio-tecnico-elotech
    username: postgres
    password: ########

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

application:
  inject:
    repository: database
